# Generated by Django 3.2.15 on 2022-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=20)),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=15)),
                ('contact_no', models.CharField(db_column='contact _no', max_length=12)),
                ('state', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
    ]
