# Generated by Django 3.2.15 on 2022-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('courier_description', models.CharField(max_length=20)),
                ('sender_name', models.CharField(max_length=15)),
                ('recepient_name', models.CharField(max_length=15)),
                ('parcel_weight', models.CharField(max_length=10)),
                ('parcel_dimension', models.CharField(max_length=15)),
                ('branch_processed', models.CharField(max_length=20)),
                ('pickup_branch', models.CharField(max_length=20)),
                ('parcel_price', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('tracking_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'shipment',
                'managed': False,
            },
        ),
    ]
